apiVersion: v1
kind: Pod
metadata:
  name: client
  namespace: s11-dns-a
spec:
  containers:
    - name: client
      image: nicolaka/netshoot:v0.13
      command: ["sleep", "3600"]
      resources:
        requests: { cpu: 5m, memory: 16Mi }
