{{- if not .Values.database.existingSecret }}
{{- $name := include "tickethub.secretName" . }}
{{- $existing := lookup "v1" "Secret" .Release.Namespace $name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels: {{- include "tickethub.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep   # never lose the DB password on uninstall
type: Opaque
data:
  DB_USER: {{ .Values.database.user | b64enc | quote }}
  {{- if and $existing $existing.data }}
  DB_PASSWORD: {{ index $existing.data "DB_PASSWORD" | quote }}
  {{- else }}
  DB_PASSWORD: {{ randAlphaNum 24 | b64enc | quote }}
  {{- end }}
{{- end }}
