apiVersion: v1
kind: ConfigMap
metadata:
  name: tickethub-config
  namespace: tickethub-raw
  labels: {app.kubernetes.io/part-of: tickethub}
data:
  APP_ENV: raw-manifests
  LOG_LEVEL: INFO
  DEFAULT_TEAM: L1 Support
  DB_HOST: tickethub-postgres
  DB_PORT: "5432"
  DB_NAME: tickethub
