apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynamic-storage
spec:
  replicas: 1
  selector:
    matchLabels: { app: dynamic-storage }
  template:
    metadata:
      labels: { app: dynamic-storage }
    spec:
      containers:
        - name: app
          image: busybox:1.36
          command: ["sh", "-c", "while true; do sleep 30; done"]
          volumeMounts:
            - name: data
              mountPath: /data
          resources: { requests: { cpu: 10m, memory: 16Mi } }
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: dynamic-pvc
